name: "web-app"
mode: "dev"
port: 8081
version: "v0.0.1"
start_time: "2020-07-01"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "web-app.log"
  max_size: 200
  max_age: 30
  max_backups: 7


mysql:
  host: "127.0.0.1"
  port: 3307
  user: "root"
  password: "781129"
  dbname: "bluebell"
  max_open_conns: 100              # 最大打开连接数（优化后减少）
  max_idle_conns: 20               # 最大空闲连接数（优化后减少）
  conn_max_lifetime: 30            # 连接最大生命周期(分钟)
  conn_max_idle_time: 15           # 连接最大空闲时间(分钟)
  enable_read_write_split: false   # 是否启用读写分离（暂时关闭）
  read_hosts: []                   # 读库地址列表（暂时为空）

redis:
  host: "127.0.0.1"
  port: 6379
  password: "781129"
  db: 0
  pool_size: 10